language: ruby
rvm:
- 2.6.0

jdk:
- openjdk12

install:
- bundle install
- pip install --user html5validator
- pip install --user yamale
- npm install
- pip install --user yamllint

before_script:
- jekyll serve &

script:
- bundle exec jekyll build
- htmlproofer --disable-external --allow-hash-href ./_site
- html5validator --root _site/
- yamale -s schemaCode.yaml _data/code
- yamale -s schemaAdmin.yaml _data/administrations
- yamale -s schemaSoftware.yaml _data/software
- npm run lint
- yamllint -d configYamlLint.yml _data
- npx cypress run


sudo: false