---

id: code

formGroups:
  - preset: adminCode
  - preset: empty
    title: releases
    param: {start: true}
  - preset: team
  - preset: selectCode
  - preset: status
  - preset: description
  - preset: category
  - preset: tags
  - preset: contact
  - widget: group
    title: partners
    param: {more: true, required: false}
    fields:
      - widget: string-i18n
        title: name
        param: {rule: alphanum-space, required: false}
      - widget: string
        title: email
        param: {type: email, required: false}
  - preset: dates
    param: {created: true}
  - widget: string-i18n
    title: repositoryUrl
    param: {type: url}
  - preset: homepageURL
    param: {type: url, required: false}
  - widget: string-i18n
    title: downloadUrl
    param: {type: url, required: false}
  - preset: licences
    param: {more: true}
  - preset: languages
  - preset: relatedCode
    param: {more: true}
  - preset: empty
