---

id: software

formGroups:
  - preset: selectSoftware
  - widget: string-i18n
    title: organization
    param: {rule: alphanum-space, required: false}
  - preset: description
  - preset: category
  - preset: homepageURL
    param: {type: url}
  - preset: licences
    param: {more: true}
  - preset: tags
  - preset: empty
    title: administrations
    param: {start: true}
  - preset: adminCode
  - preset: empty
    title: uses
    param: {start: true}
  - preset: contact
    param: {phone: false}
  - preset: dates
    param: {started: true}
  - preset: empty
  - preset: empty
