---

id: code

formGroups:
  - preset: schemaVersion
  - preset: adminCode
  - preset: contact
  - preset: dates
  - preset: description
  - widget: string-i18n
    title: DownloadUrl
    type: url
    required: false
  - widget: string-i18n
    title: HomepageUrl
    type: url
    required: false
  - preset: languages
  - widget: string-i18n
    title: ProjectName
    rule: alphanum-space
  - widget: string-i18n
    title: Organization
    rule: alphanum-space
    required: false
  - widget: group
    title: Partner
    required: false
    fields:
      - widget: string-i18n
        title: Url
        type: url
      - widget: email
      - widget: string-i18n
        title: Name
        rule: alphanum-space
  - preset: licenses
  - widget: string-i18n
    title: RepositoryUrl
    type: url
  - widget: group
    title: RelatedCode
    required: false
    fields:
      - widget: string-i18n
        title: Url
        type: url
      - widget: string-i18n
        title: Name
        rule: alphanum-space
  - preset: tags
  - widget: select
    title: Status
    required: false
<<<<<<< HEAD
    options: [ alpha, beta, maintained, deprecated, retired ]
=======
    options: [alpha, beta, maintained, deprecated, retired]
>>>>>>> a820a6418c4faf5e4a3c70810d8f09a3be49ad90
  - widget: string
    title: VersionProject
    required: false
  - widget: string
    title: Vcs
    required: false
    rule: alphanum-space
