---

id: oss

formGroups:
  - preset: schemaVersion
  - preset: description
  - preset: homepageUrl
  - preset: licenses
  - widget: string-i18n
    title: name
    rule: alphanum-space
  - preset: tags
  - preset: empty
    start: true
    title: administrations
  - preset: adminCode
  - preset: empty
    start: true
    title: uses
  - preset: contact
    phone: false
  - preset: dates
    started: true
  - widget: string-i18n
    title: name
    prepend: use
    rule: alphanum-space
  - widget: string-i18n
    title: description
    prepend: use
    rule: alphanum-space
  - preset: relatedCode
  - preset: status
  - preset: empty
  - preset: empty
