---

id: standard

formGroups:
  - preset: schemaVersion
  - preset: selectStandard
  - widget: string-i18n
    title: name
    rule: alphanum-space
  - preset: description
  - widget: string-i18n
    title: specURL
    type: url
  - widget: string-i18n
    title: standardOrg
  - preset: tags
  - preset: hr
  - preset: empty
    start: true
    title: administrations
  - preset: adminCode
  - widget: group
    title: reference
    more: true
    fields:
      - widget: string-i18n
        title: URL
        type: url
      - widget: string-i18n
        title: name
        rule: names
  - preset: dates
    created: true
    metadata: true
  - widget: string
    title: status
  - preset: contact
    phone: false
    required: true
  - preset: empty
