---

id: research

formGroups:
  - preset: selectResearch
  - preset: description
  - preset: category
  - preset: tags
  - preset: homepageURL
    param: {type: url}
  - preset: licences
    param: {more: true}
  - preset: empty
    title: administrations
    param: {start: true}
  - preset: adminCode
  - preset: team
  - preset: empty
    title: uses
    param: {start: true}
  - preset: contact
    param: {phone: false}
  - widget: string
    title: date
    param: {type: date, rule: dateISO}
  - preset: empty
  - preset: empty
