---
contact:
  email: libre@ville.montreal.qc.ca
date:
  started: '2017-06-30'
  metadataLastUpdated: '2019-05-06'
description:
  en: Developpement.
  fr: Développement.
name:
  en: Development environment software.
  fr: Logiciels environnement de développement.
