---
contact:
  email: ilia.salem@tbs-sct.gc.ca
date:
  started: '2019-05-06'
  metadataLastUpdated: '2019-05-13'
name:
  en: Development and deployment
  fr: Développements et Déploiements
description:
  en: Digital Collaboration Division development and deployment
  fr: >-
    Développement et déploiement de la Division de la collaboration
    numérique
